export const categories = {
  direction: [
    'icon-send',
    'icon-receive',
    'icon-download',
    'icon-search',
    'icon-close',
    'icon-settings',
    'icon-filter',
    'icon-qrmini',
    'icon-script',
    'icon-json',
    'icon-fullscreen',
    'icon-exitfullscreen',
    'icon-copy',
    'icon-chevronup',
    'icon-chevrondown',
    'plus',
    'left',
    'right',
    'icon-unpin',
    'icon-arrowdown',
    'icon-arrowup',
    'icon-dexmini',
    'icon-copylarge',
    'icon-menu',
    'icon-qrlarge',
    'icon-menuwalletoutlined',
    'icon-menutokenoutlined',
    'icon-menudexoutlined',
    'icon-menusettingoutlined',
    'icon-menuexit',
    'icon-menulogin',
    'icon-settinggeneraloutlined',
    'icon-settinginfooutlined',
    'icon-settingnetworkoutlined',
    'icon-settingsecurityoutlined',

    'icon-chrome',
    'icon-firefox',
    'icon-opera',
    'icon-safari',
    'icon-anonim',
    'icon-passbrowser',
    'icon-refreshbrowser',
    'icon-backup',
    'icon-shredder',
    'icon-mailopen',
    'icon-os',
    'icon-wifi',
    'icon-link',
    'icon-plugin',

    'icon-menuwalletfilled',
    'icon-menutokenfilled',
    'icon-menufexfilled',
    'icon-assetsfilled',
    'icon-transactionfilled',
    'icon-portfoliofilled',
    'icon-leasingfilled',

    'icon-settinggeneralfilled',
    'icon-settinginfofilled',
    'icon-settingnetworkfilled',
    'icon-settingsecurityfilled',
    'icon-circlequestion',
    'icon-circlesubmit',
    'icon-circlecheckfilled',
    'icon-circleerrorfilled',
    'exclamation-circle',
    'icon-lockfilled',
    'icon-dotsvertical',
    'icon-triangleselectup',
    'icon-triangleselectdown',
    'icon-triangleright',
    'icon-check',
    'icon-ledgermini',
    'icon-keepermini',
    'down',
    'calendar',
    'loading',
    'icon-procent',
    'eye',
    'eye-invisible',
    'close',
    'upload',
    'delete',
    'check-circle',
    'info-circle',
    'warning-circle',
    'error-circle',
    'script-mini',
  ],
  transactions: [
    'step-forward',
  ],
};

export interface Categories {
  direction: string[];
  transactions: string[];
}

export type CategoriesKeys = keyof Categories;
